name: CI_PUSH
on:
  push:
    branches:
      # - "**"
      - ci-update

jobs:
  push:
    strategy:
      matrix:
        step: ["lint", "format", "build"]
        node-version: [16.x]

    name: Push commits - ${{ matrix.step }}
    runs-on: ubuntu-latest
    
    steps: 
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ${{ matrix.step }}
        if: always()
        run: |
          npm ci --ignore-scripts
          npm run ${{ matrix.step }}
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Commit & ${{ matrix.step }} processed"

