name: CI_PUSH
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - dev
      - next
      - main

jobs:
  push:
    strategy:
      matrix:
        node-version: [16.x]

    name: Commit or PR
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci --ignore-scripts
      - run: npm run lint && npm run format && npm run build

      - name: test name
        # if: github.event_name == 'push' && github.event.push.base.ref == 'ci-update'
        if: ${{ github.event_name == 'push' && github.event.push.base.ref == 'ci-update' }}
        run: echo "Ceci est un test sur la branche ci-update."
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Commit or PR processed"

